# Copyright (c) 2024 Nordic Semiconductor ASA
# SPDX-License-Identifier: BSD-3-Clause

manifest:
  remotes:
    - name: zephyr
      url-base: https://github.com/zephyrproject-rtos
    - name: ncs
      url-base: https://github.com/nrfconnect
  defaults:
    remote: zephyr
  projects:
    # For testing with nRF boards
    - name: zephyr
      repo-path: zephyr
      revision: main
      import:
        name-allowlist:
          - hal_nordic
          - picolibc
          - cmsis
          - cmsis-dsp
          - cmsis-nn
          - trusted-firmware-m
          - mbedtls
          - mcuboot
        name-blacklist:
          - nrf_wifi
    # nRF70 Wi-Fi OSAL library
    - name: nrf_wifi
      repo-path: nrf_wifi
      revision: a4e0a470fffdead2af5bcd63eac050b6614a7281
      path: modules/lib/nrf_wifi
    # nRF70 Wi-Fi firmware blobs (without west blobs fetch)
    - name: nrfxlib
      remote: ncs
      repo-path: sdk-nrfxlib
      revision: 85954588939b0d6c46a84ae39ef7926cc2fe9810
      path: nrfxlib
