name: Documentation Build and reploy

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - 'v*-branch'
  push:
    branches:
      - main
      - 'v*-branch'
    tags:
      - v*

env:
  DOXYGEN_VERSION: 1.12.0
  DOXYGEN_MD5SUM: fd96a5defa535dfe2e987b46540844a4

jobs:
  build:
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout sources
        uses: nrfconnect/action-checkout-west-update@main
        with:
          path: nrf70_bm_ws/nrf70-bm

      - name: cache-pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-doc-pip

      - name: Install packages
        working-directory: nrf70_bm_ws
        run: |
          sudo apt-get update
          sudo apt-get install -y wget python3-pip git ninja-build graphviz lcov
          wget --no-verbose "https://github.com/doxygen/doxygen/releases/download/Release_${DOXYGEN_VERSION//./_}/doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz"
          echo "${DOXYGEN_MD5SUM}  doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz" | md5sum -c
          if [ $? -ne 0 ]; then
            echo "Failed to verify doxygen tarball"
            exit 1
          fi
          sudo tar xf doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz -C /opt
          echo "/opt/doxygen-${DOXYGEN_VERSION}/bin" >> $GITHUB_PATH
          echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: 3.12
          cache: pip
          cache-dependency-path: zephyr/doc/requirements.txt

      - name: install-pip
        working-directory: nrf70_bm_ws
        run: |
          pip install -r zephyr/doc/requirements.txt
          pip install breathe

      - name: West zephyr-export
        working-directory: nrf70_bm_ws
        run: |
          west zephyr-export

      - name: Build documentation
        working-directory: nrf70_bm_ws/nrf70-bm
        run: ./build-docs.sh

      - name: Prepare legacy upload
        if: ${{ github.ref == 'refs/heads/main' || !contains(github.event.pull_request.labels.*.name, 'external') || contains(github.event.pull_request.labels.*.name, 'CI-trusted-author') }}
        working-directory: nrf70_bm_ws/nrf70-bm/nrf70_bm_lib
        run: |
          MONITOR="monitor_${{ github.run_id }}.txt"

          # Create documentation upload files
            if [[ "${{ github.event_name }}" == "pull_request" ]]; then
              ARCHIVE="nrf70-bm-docs-${{ github.event.number }}.zip"
              echo "publish2 dev PR-${{ github.event.number }} ${ARCHIVE}" > "${MONITOR}"
              echo "${{ github.event.number }}" > pr.txt
            else
              if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
                ARCHIVE="nrf70-bm-docs-main-$${{ github.sha }}.zip"
                echo "publish2 main ${ARCHIVE}" > "${MONITOR}"
              else
                echo "Neither PR nor main branch, exiting"
                exit 0
              fi
            fi

          cd docs/build/html
          zip -rq "${ARCHIVE}" .
          mv "${ARCHIVE}" ../../../

      - name: Store
        if: ${{ github.ref == 'refs/heads/main' || !contains(github.event.pull_request.labels.*.name, 'external') || contains(github.event.pull_request.labels.*.name, 'CI-trusted-author') }}
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: |
            nrf70_bm_ws/nrf70-bm/nrf70_bm_lib/*.zip
            nrf70_bm_ws/nrf70-bm/nrf70_bm_lib/monitor*.txt
            nrf70_bm_ws/nrf70-bm/nrf70_bm_lib/pr.txt

      - name: Setup pages
        if: github.event_name != 'pull_request'
        uses: actions/configure-pages@v4

      - name: Upload pages artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-pages-artifact@v3
        with:
          path: nrf70_bm_ws/nrf70-bm/nrf70_bm_lib/docs/build/html

      - name: Upload artifacts
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          path: nrf70_bm_ws/nrf70-bm/nrf70_bm_lib/docs/build/html

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    if: github.event_name != 'pull_request'
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
